- name: Touch Ansistrono shared files
  file:
    state: touch
    path: "{{ ansistrano_shared_path }}/{{ item }}"
  with_items: "{{ ansistrano_shared_files }}"

- name: Make Ansistrono shared dirs
  file:
    state: directory
    path: "{{ ansistrano_shared_path }}/{{ item }}"
  with_items: "{{ ansistrano_shared_paths }}"
