# Generated by Django 2.1.5 on 2019-06-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
