# Generated by Django 2.1.5 on 2019-08-25 16:56

from django.db import migrations, models
import django.db.models.deletion
import scraper.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapingtask_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(validators=[scraper.models.validate_yaml])),
            ],
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='task',
            field=models.TextField(validators=[scraper.models.validate_yaml]),
        ),
        migrations.AddField(
            model_name='item',
            name='scraping_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.ScrapingTask'),
        ),
    ]
