# Generated by Django 2.1.5 on 2019-08-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20190831_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapingjob',
            old_name='task',
            new_name='scraping_task',
        ),
    ]
