# Generated by Django 2.1.5 on 2019-09-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20190831_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapingjob',
            name='scraping_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.ScrapingTask'),
        ),
    ]
