# Generated by Django 2.1.5 on 2019-11-17 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20190901_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_found',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
