# Generated by Django 2.1.5 on 2019-11-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_item_date_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='scraping_job',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
