# Generated by Django 2.1.5 on 2019-11-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20191117_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='was_run_today',
            field=models.BooleanField(default=False),
        ),
    ]
