# Generated by Django 2.2.7 on 2019-12-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_scrapingjob_was_run_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='identifier',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
