# Generated by Django 2.2.7 on 2019-12-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20191202_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='identifier',
            field=models.TextField(default=''),
        ),
    ]
