# Generated by Django 2.2.7 on 2019-12-04 17:37

from django.db import migrations, models
import django.db.models.deletion
import scraper.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_auto_20191204_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='data',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_found',
        ),
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(validators=[scraper.models.validate_yaml])),
                ('date_found', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.Item')),
            ],
        ),
    ]
