# Generated by Django 2.2.9 on 2019-12-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_auto_20191204_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemstate',
            options={'ordering': ['-date_found']},
        ),
        migrations.CreateModel(
            name='ScrapingJobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_run', models.DateTimeField(auto_now_add=True)),
                ('result', models.IntegerField(choices=[('OK_NEW', 'New results available'), ('OK_NONEW', 'No new results available'), ('PAGE_UNAVAILABLE', 'Page not available')])),
                ('scraping_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.ScrapingJob')),
            ],
        ),
    ]
