# Generated by Django 2.2.9 on 2020-01-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_auto_20191222_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapingjoblog',
            options={'ordering': ['-date_run']},
        ),
    ]
