# Generated by Django 2.2.9 on 2020-01-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0018_auto_20200106_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingjob',
            name='multiple',
        ),
    ]
