# Generated by Django 2.2.9 on 2020-01-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_remove_scrapingjob_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(default='dummy.com'),
            preserve_default=False,
        ),
    ]
