# Generated by Django 2.2.9 on 2020-01-11 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0021_item_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRunner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField(default=datetime.datetime(2020, 1, 11, 11, 53, 16, 153686))),
            ],
            options={
                'verbose_name': 'Job runner',
            },
        ),
    ]
