# Generated by Django 2.2.9 on 2020-01-11 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0022_jobrunner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunner',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 11, 53, 47, 674537)),
        ),
    ]
