# Generated by Django 2.2.9 on 2020-01-11 12:09

import datetime
from django.db import migrations, models
import scraper.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0023_auto_20200111_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='cron',
            field=models.TextField(default='0 9 */1 * *', validators=[scraper.models.validate_cron]),
        ),
        migrations.AlterField(
            model_name='jobrunner',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 12, 9, 54, 724203)),
        ),
    ]
