# Generated by Django 2.2.9 on 2020-01-11 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0024_auto_20200111_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunner',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
