# Generated by Django 2.2.9 on 2020-01-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0025_auto_20200111_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingjob',
            name='running_time',
        ),
        migrations.RemoveField(
            model_name='scrapingjob',
            name='was_run_today',
        ),
    ]
