# Generated by Django 2.2.9 on 2020-02-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0027_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='mail_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
    ]
