- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Add nginx config
  become: yes
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
    mode: 0644

- name: Install nginx config
  become: yes
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link

- name: Reload nginx systemd service
  become: yes
  systemd:
    name: nginx
    enabled: yes
    state: reloaded

- name: ufw - allow nginx
  become: yes
  ufw:
    rule: allow
    name: OpenSSH
