- name: Create a deploy user
  become: yes
  user:
    name: deploy
    groups: sudo
    state: present
    shell: /bin/bash

- name: Add sudoers.d setup for a deploy user
  become: yes
  template:
    src: deploy.j2
    dest: /etc/sudoers.d/deploy
    mode: 0644

- name: Set authorized key taken from file
  become: yes
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('file', item) }}"
  with_items: "{{ provision_public_keys }}"

- name: Disallow password authentication
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: Disallow root SSH access
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh

- name: Update APT package cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Update server
  become: yes
  apt:
    upgrade: safe

- name: Install packages
  become: yes
  apt:
    pkg: "{{ provision_packages }}"
    state: present

- name: Setup unattended upgrades
  become: yes
  copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/
  with_items:
    - 10periodic
    - 50unattended-upgrades
  when: "'unattended-upgrades' in provision_packages"

- name: Setup ufw
  become: yes
  ufw:
    state: enabled
    policy: deny
  when: "'ufw' in provision_packages"

- name: ufw - ssh
  become: yes
  ufw:
    rule: allow
    name: OpenSSH
  when: "'ufw' in provision_packages"

- name: Setup logwatch config
  become: yes
  copy:
    src: "logwatch.conf"
    dest: /etc/logwatch/conf/logwatch.conf
  when: "'logwatch' in provision_packages"

- name: stat logwatch daily cron
  stat:
    path: /etc/cron.daily/00logwatch
  register: logwatch_cron_daily

- name: Change logwatch to weekly
  become: yes
  command: mv /etc/cron.daily/00logwatch /etc/cron.weekly/00logwatch
  when: logwatch_cron_daily.stat.exists

