- hosts: ubuntu-droplet
  remote_user: ellox
  vars:
    app_name: deals
    domain_list:
      - "deals.ellox.science"
      - "www.deals.ellox.science"
    certbot_admin_email: "maciek.matczak@gmail.com"
    certbot_domain_list: "{{ domain_list }}"
    nginx_domain_list: "{{ domain_list }}"
  roles:
    - checksudo
    - certbot
    - nginx
