- hosts: webserver
  remote_user: "{{ remote_user }}"
  vars:
    app_name: "{{ playbook_dir | dirname | basename }}"
    ansistrano_deploy_from: "{{ playbook_dir | dirname }}/"
    ansistrano_deploy_to: "/home/{{ ansible_ssh_user  }}/deployed/{{ app_name }}/"
    ansistrano_before_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/touch_before_symlink.yml"
    ansistrano_shared_files:
      - ".env"
      - "db.sqlite3"
      - "chromedriver"
    ansistrano_shared_paths:
      - "venv"
      - "static"
      - "media"
    ansistrano_keep_releases: 5
    ansistrano_deploy_via: rsync
    ansistrano_rsync_extra_params:
      - "--exclude=venv"
      - "--exclude=.mypy_cache"
      - "--exclude=.vscode"
      - "--exclude=__pycache__"
      - "--exclude=db.sqlite3"
  roles:
    - checksudo
    - ansistrano.deploy
    - django_app
    - cron
