- hosts: webserver
  remote_user: "{{ remote_user }}"
  vars:
    app_name: "{{ playbook_dir | dirname | basename }}"
    domain_list:
      - "deals.ellox.science"
      - "www.deals.ellox.science"
    certbot_admin_email: "maciek.matczak@gmail.com"
    certbot_domain_list: "{{ domain_list }}"
    nginx_domain_list: "{{ domain_list }}"
  roles:
    - checksudo
    - certbot
    - nginx
